type: object
required:
- splunk_token
properties:
  splunk_token:
    type: string
  cors_allowed_origins:
    type: array
    items:
      type: string
    nullable: true
  cors_allowed_headers:
    type: array
    items:
      type: string
    nullable: true